In [6]:
#question d

import numpy as np
mod = 10*9+7
#10のn乗を13で割った時のあまり(十進法だから)
a = 10 ** np.arange(6) % 13
#0~9の一次元配列を6個(10で割った時のループ数)
b = np.tile(np.arange(10),(6, 1))
print(b)
#b.Tはtの転置行列
c = a * b.T % 13
print(c)


[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]
[[ 0  0  0  0  0  0]
 [ 1 10  9 12  3  4]
 [ 2  7  5 11  6  8]
 [ 3  4  1 10  9 12]
 [ 4  1 10  9 12  3]
 [ 5 11  6  8  2  7]
 [ 6  8  2  7  5 11]
 [ 7  5 11  6  8  2]
 [ 8  2  7  5 11  6]
 [ 9 12  3  4  1 10]]
